SCREEN_WIDTH = 1920
SCREEN_HEIGHT = 1080
ENEMY_MIN_RADIUS = 20
ENEMY_KINDS = 3
ENEMY_SPAWN_RATE = 0.8  # seconds
ENEMY_MAX_RADIUS = ENEMY_MIN_RADIUS * ENEMY_KINDS
ENEMY_SPEED = 50
PLAYER_RADIUS = 20
PLAYER_TURN_SPEED = 300
PLAYER_SPEED = 200
PLAYER_SHOOT_SPEED = 1000

SHOT_RADIUS = 5
SHOT_TIMER = 0 
PLAYER_SHOOT_CD = 0.1

GAME_OVER = "game_over"
PLAYING = "playing"

